-- Biblioteca de ejercicios real de DIPRA (migrada desde seedData() en dipra-app.jsx)

insert into public.biblioteca_ejercicios (nombre, link) values
  ('90-90 hamst stretch', 'https://www.youtube.com/shorts/oJJifjdUUXk'),
  ('90-90 hamstring', 'https://www.youtube.com/shorts/oJJifjdUUXk'),
  ('90-90 hip mob', 'https://www.youtube.com/shorts/WGlR_mISMo0'),
  ('90-90 shinbox', 'https://www.youtube.com/shorts/9nhhZIpIZ7A'),
  ('Arm bar', 'https://www.youtube.com/watch?v=IAByZREjXp8'),
  ('Back squat', 'https://www.youtube.com/shorts/8B8UUspQ2bY'),
  ('Banded hip flexor', 'https://www.youtube.com/watch?v=AzaVcEgAj28'),
  ('banded TK Rot mob', 'https://www.youtube.com/watch?v=pPTbGIJHPIo'),
  ('BB bench press', 'https://www.youtube.com/watch?v=ejI1Nlsul9k'),
  ('BB DL Convencional', 'https://www.youtube.com/shorts/A-R_fuvVgGM'),
  ('BB DLR', 'https://www.youtube.com/shorts/IGt0IfvtN0M'),
  ('BB Split jerk', 'https://www.youtube.com/watch?v=PsiO8lZTU2I'),
  ('biceps curl', 'https://www.youtube.com/watch?v=HnHuhf4hEWY'),
  ('Bootstrap stretch', 'https://www.youtube.com/shorts/yQ7u_thcJHw'),
  ('Broad jump', 'https://www.youtube.com/shorts/v0yrBWA3eEs'),
  ('Cable triceps extensión', 'https://www.youtube.com/shorts/xguGXQAvbKk'),
  ('DB drop to split', 'https://www.youtube.com/shorts/pItWCTF20JM'),
  ('Db goodmoorning', 'https://www.youtube.com/shorts/_Q1nno1HT_8'),
  ('Db single leg calf raises', 'https://www.youtube.com/shorts/E1mG5L9rpFc'),
  ('Dobule calf raises', 'https://www.youtube.com/shorts/VvVYByY_kmA'),
  ('Farmer walk', 'https://www.youtube.com/watch?v=8OtwXwrJizk'),
  ('floatin heel split squat', 'https://www.youtube.com/shorts/aBMIFChtXe4'),
  ('Fondos', 'https://www.youtube.com/shorts/h0rxpVVBnnA'),
  ('Half kneeling hip cars', 'https://www.youtube.com/shorts/RsZQfyVbdqc'),
  ('hang power clean', 'https://www.youtube.com/watch?v=0aP3tgKZcHQ'),
  ('Hip thrust', 'https://www.youtube.com/shorts/rVMsqygXtG4'),
  ('Hip thrust single leg', 'https://www.youtube.com/shorts/bRZeB6UG6Js'),
  ('HK shoulder press', 'https://www.youtube.com/shorts/cMbbUjhNVws'),
  ('HK windmill', 'https://www.youtube.com/shorts/Ygwg1cZktjE'),
  ('Iso glute bridge', 'https://www.youtube.com/watch?v=mUEViZ1R7l4'),
  ('ISo hamstring', 'https://www.youtube.com/shorts/Fd3sFl9Hw4Y'),
  ('Iso shuffle', 'https://www.youtube.com/results?search_query=good+morinng+adductor+movement'),
  ('KB clean squat SA', 'https://www.youtube.com/watch?v=FZ8mMUwnCQs'),
  ('Kb deficit sumo squat', 'https://www.youtube.com/shorts/iv05gGqjl8k'),
  ('Kb lateral squat', 'https://www.youtube.com/shorts/XvJ8gtW30ZA'),
  ('Kb split halo', 'https://www.youtube.com/shorts/gjL9_hIFZd4'),
  ('Kb swing', 'https://www.youtube.com/shorts/moK1eINw7NY'),
  ('Knee to cheest', 'https://www.youtube.com/watch?v=FKftqzso5cA'),
  ('kneeling prayer', 'https://www.youtube.com/shorts/J6ILB6kjk-U'),
  ('Lateral pull down', 'https://www.youtube.com/watch?v=JGeRYIZdojU'),
  ('Leg curl machine o leg curl fit ball', 'https://www.youtube.com/shorts/nIj321YZWbo'),
  ('Military press', 'https://www.youtube.com/shorts/FghebqCF_o8'),
  ('montain climb at push up at burpee', 'https://www.youtube.com/shorts/Iup9gb-PhWg'),
  ('Movilidad escapular', 'https://www.youtube.com/shorts/nbxbyudorLU'),
  ('OH lunge to windmill', 'https://www.youtube.com/shorts/9Pf4aXDCojs'),
  ('Over head triceps (SA)', 'https://www.youtube.com/shorts/NTNMTSAhVuc'),
  ('Plate Elevated Static Split Jump', 'https://www.youtube.com/shorts/0S67-dautAE'),
  ('press paloff con rotacion', 'https://www.youtube.com/shorts/iAWKyMczcrs'),
  ('Pull over', 'https://www.youtube.com/shorts/EYK60fwFkGA'),
  ('Pull up (25)', 'https://www.youtube.com/shorts/PpY2Cgv2LD0'),
  ('Push up escapular + Push up (explosivo)', 'https://www.youtube.com/shorts/fGwUe8IhFO4'),
  ('quad rot spine', 'https://www.youtube.com/shorts/mlFeVRgXoag'),
  ('Quad Sh cars', 'https://www.youtube.com/shorts/1FIA6DVD4wM'),
  ('REMO EN T O inclinado', 'https://www.youtube.com/shorts/W8_kFY-u8No'),
  ('Reverse nordic', 'https://www.youtube.com/shorts/8AB6OFzD2GE'),
  ('Rot spine mob', 'https://www.youtube.com/shorts/sJlvUjb5Qg4'),
  ('Scap pull', 'https://www.youtube.com/shorts/42BPyTlr6QI'),
  ('Scorpion stretching', 'https://www.youtube.com/shorts/TbtCGq_tC9A'),
  ('Seated EPR', 'https://www.youtube.com/shorts/SMAs0dbLEcs'),
  ('Shuffle', 'https://www.youtube.com/shorts/6dTvneNsot8'),
  ('Single leg RDL', 'https://www.youtube.com/shorts/Ex_pPwkzS1k'),
  ('Step up (profundo)', 'https://www.youtube.com/shorts/Ey2H3-zmzSk'),
  ('Step up (profundo)(pistol asistida)', 'https://www.youtube.com/shorts/Ey2H3-zmzSk'),
  ('TGU', 'https://www.youtube.com/shorts/-Zsx2JTfGsU'),
  ('through pass kb', 'https://www.youtube.com/shorts/vGkkOGVjWns'),
  ('WGS', 'https://www.youtube.com/shorts/OCXMbIzYJTQ'),
  ('YtWS', 'https://www.youtube.com/watch?v=v6p7aiVuPy4');
